spring.application.name=jobmanager
spring.datasource.url=jdbc:postgresql://localhost:5432/jobmanager
spring.datasource.username=postgres
spring.datasource.password=Es5303PSQL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true